# Ambiente Local (NÃO REMOVER O spring.profiles.active=local se estiver rodando no seu PC)
spring.profiles.active=local
server.port=${PORT:8080}

# Chaves de API (Valores vazios por padrão para o GitHub)
ai.api.key=${GEMINI_API_KEY:}
ai.model.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# URL do calendário da faculdade
# Calendário
calendar.matutino.a.url=${CALENDAR_MATUTINO_A_URL:}
calendar.matutino.b.url=${CALENDAR_MATUTINO_B_URL:}
calendar.noturno.a.url=${CALENDAR_NOTURNO_A_URL:}
calendar.noturno.b.url=${CALENDAR_NOTURNO_B_URL:}

# Painel Admin
admin.user=${ADMIN_USER:}
admin.password=${ADMIN_PASSWORD:}

# Segurança (Mitigação de Vulnerabilidades XSS e Bypass)
server.error.include-stacktrace=never
server.servlet.session.cookie.http-only=true

# Multipart Upload Limits 
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
