# Ambiente Local (NÃO REMOVER O spring.profiles.active=local se estiver rodando no seu PC)
spring.profiles.active=local
server.port=${PORT:8080}

# Chaves de API (Valores vazios por padrão para o GitHub)
ai.api.key=${GEMINI_API_KEY:}
ai.model.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# URL do calendário da faculdade
calendar.url=${CALENDAR_URL:}
